### ISSUE TITLE
Inference got wrong result in debug profile

### ISSUE THREAD

**Issue by sbant** [jamjamjon/usls#113]
My app use usls with db model, and got wrong result in debug profile. I used to get right result in February this year maybe with old version of usls.

Then I tried usls's db example, got right result in release profile, but wrong result in debug profile.

Last I tried change app Cargo.toml  usls's opt-level
```
[profile.dev.package.usls]
opt-level = 0
```

opt-level = 0 , got wrong result
opt-level = 1 2 3 , got right result

Is there anything can be done?

![Image](https://github.com/user-attachments/assets/38a67b56-d5e3-48c6-b86f-0b707e50dbed)

**Comment by jamjamjon** [comment]
I have made the following attempts, and all results are correct. I am unable to reproduce your issue:

* Versions tested: `usls = "0.1.0-rc.1"` and `usls = { git = "https://github.com/jamjamjon/usls" }`
* `dev` profile `opt-level` set to 0, 1, 2, and 3
* `release` profile `opt-level` set to 0, 1, 2, and 3
* Os: linux


```toml
[dependencies]
usls = "0.1.0-rc.1"
# usls = { git = "https://github.com/jamjamjon/usls" }
anyhow = "1.0.98"
argh = "0.1.13"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }

[profile.dev.package.usls]
opt-level = 0
# opt-level = 1
# opt-level = 2
# opt-level = 3

[profile.release.package.usls]
opt-level = 0
# opt-level = 1
# opt-level = 2
# opt-level = 3


```
All cases returned the expected results.


----
What version of `usls` are you using?
What platform are you running on?
And what version of Rust and operating system environment are you using?
