### ISSUE TITLE
Update usls crate

### ISSUE THREAD

**Issue by egorsmkv** [jamjamjon/usls#74]
<img width="802" alt="Image" src="https://github.com/user-attachments/assets/6f5e02a0-c0f7-4b72-9b35-786814f11c89" />

Seems like the version there is too old

**Comment by jamjamjon** [comment]
It’s true that the crate on crates.io hasn’t been updated for a while. You can use the latest version by specifying:
```toml
[dependencies]
usls = { git = "https://github.com/jamjamjon/usls", rev = "commit-sha" }
```
I’ll be updating the project soon and will publish a new version to crates.io then. @egorsmkv
